// <auto-generated />
namespace BillingSystemDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_invoiceItem_newPK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_invoiceItem_newPK));
        
        string IMigrationMetadata.Id
        {
            get { return "202203190000241_update_invoiceItem_newPK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
